# Stage 1: Install dependencies
# We use node:20-alpine for a lightweight, secure base.
# libc6-compat is required for some native node modules to compile on alpine.
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

# Stage 2: Rebuild the source code
# This compiles TypeScript, applies Tailwind CSS v4, and generates the production bundle.
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1
# NEXT_PHASE disables Zod env check crashes during static building
ENV NEXT_PHASE 1

RUN npm run build

# Stage 3: Runner
# The final runtime image contains ONLY files generated by standalone output.
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Setup a non-root system user for container security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for Next.js prerender caching
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Leverage output traces to reduce image size (only standalone resources are copied)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# server.js is generated by Next.js output: 'standalone'
CMD ["node", "server.js"]
